server {
    server_name snowsong.top www.snowsong.top;

    root /var/www/mysite;
    index index.html;

    # 字符集
    charset utf-8;

    # 日志
    access_log /var/log/nginx/mysite-access.log;
    error_log /var/log/nginx/mysite-error.log;

    include /etc/nginx/snippets/agentdemo.locations.conf;

    # 主站点
    location / {
        try_files $uri $uri/ $uri.html =404;
    }

    # 安全头
    add_header X-Content-Type-Options nosniff;
    add_header X-Frame-Options SAMEORIGIN;

    # 禁止访问隐藏文件
    location ~ /\. {
        deny all;
    }

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/snowsong.top/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/snowsong.top/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = snowsong.top) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    listen [::]:80;
    server_name snowsong.top www.snowsong.top;
    return 404; # managed by Certbot


}
